const API_URL="https://dpiecktmpduhlapnkwvq.supabase.co";
const API_KEY="sb_publishable_WCj-w-p_KTzKoO9pDqGbVQ_ye8VdCOd";
const featured= document.querySelector("#featured-products");
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function get(path){const r=await fetch(API_URL+"/rest/v1/"+path,{headers:{apikey:API_KEY,Authorization:"Bearer "+API_KEY}});if(!r.ok)throw new Error("Products unavailable");return r.json();}
function addToCart(p){let cart=[];try{cart=JSON.parse(localStorage.getItem("drop-cart")||"[]");if(!Array.isArray(cart))cart=[];}catch{}const found=cart.find(x=>String(x.id)===String(p.id));if(found)found.qty=Math.max(1,Number(found.qty)||1)+1;else cart.push({id:p.id,n:p.name,p:Number(p.selling_price),img:p.image_url||"",e:"🛍️",qty:1});localStorage.setItem("drop-cart",JSON.stringify(cart));const b=document.querySelector('[data-add="'+CSS.escape(String(p.id))+'"]');if(b){b.textContent="Added ✓";b.disabled=true;setTimeout(()=>{b.textContent="Add to cart +";b.disabled=false},1300)}}
async function loadFeatured(){try{const products=await get("products?select=id,name,selling_price,image_url,category_id&active=eq.true&order=created_at.desc&limit=4");let categories=[];try{categories=await get("categories?select=id,name")}catch{}const cats=new Map(categories.map(c=>[c.id,c.name]));if(!products.length){featured.innerHTML='<p class="empty-state">New finds are on their way. <a href="./index.html#shop">Browse the shop ↗</a></p>';return;}featured.innerHTML=products.map(p=>'<article class="product-card"><a href="./index.html#shop" class="product-image" aria-label="View '+esc(p.name)+'">'+(p.image_url?'<img src="'+esc(p.image_url)+'" alt="'+esc(p.name)+'" loading="lazy">':'<span class="product-placeholder">✳</span>')+'</a><div class="product-info"><h3>'+esc(p.name)+'</h3><div class="product-price">'+money(p.selling_price)+'</div><div class="product-category">'+esc(cats.get(p.category_id)||"A good find")+'</div><button class="add-button" data-add="'+esc(p.id)+'">Add to cart +</button></div></article>').join("");featured.querySelectorAll("[data-add]").forEach(btn=>btn.addEventListener("click",()=>{const p=products.find(x=>String(x.id)===btn.dataset.add);if(p)addToCart(p)}));}catch(e){console.warn("Could not load showroom products",e);featured.innerHTML='<p class="empty-state">Our picks are taking a little break. <a href="./index.html#shop">Browse all products ↗</a></p>';}}
document.querySelectorAll("[data-category-link]").forEach(a=>a.addEventListener("click",()=>{try{sessionStorage.setItem("storefront-view",JSON.stringify({category:a.dataset.categoryLink,page:1,search:""}))}catch{}}));
loadFeatured();
